- id: doi:10.1158/0008-5472.CAN-21-0384
  image: https://img1.imgtp.com/2022/08/31/TIVfqyiI.png
  date: 2020-6-2
  tags:
    - IDH1-Mutant
    - Radiation

- id: doi:10.1007/s00018-021-04068-2
  image: https://img1.imgtp.com/2022/08/31/QZBG3Imb.jpeg
  tags:
    - Small RNA-Seq
    - Proteomics
    - Extracellular Vesicles
    - Haptotaxis

- id: doi:10.3390/cells9102243
  image: https://img1.imgtp.com/2022/08/31/UT10SAzD.jpeg
  tags:
    - delta-9-tetrahydrocannbinol (THC)
    - extracellular vesicles (EVs)
    - SIV/HIV

- id: doi:10.1016/j.apsb.2021.09.032
  image: https://img1.imgtp.com/2022/08/31/2gFNpF6Y.jpeg
  tags:
    - Fibroblast activation protein
    - Nasopharyngeal cancer
    - PET

- id: doi:10.2147/CMAR.S228174
  image: https://img1.imgtp.com/2022/08/31/4D7rMDhF.jpeg
  tags:
    - TAAs
    - TME
    - gene expression score
    - glioblastoma
    - prognosis
