- id: doi:10.1158/0008-5472.CAN-21-0384
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
  date: 2020-6-2
  tags:
    - IDH1-Mutant
    - Radiation

- id: doi:10.1007/s00018-021-04068-2
  image: https://www.jianguoyun.com/c/tblv2/N48n1e7_HdYWAa4v9I9emBiTBuYuO2QH0HynpPVhW5zxQzE7JPa-wjddSo46_ftc2kBYjqHo/YsuLPPy3CnZbwCPWhGVmUQ/l
  tags:
    - Small RNA-Seq
    - Proteomics
    - Extracellular Vesicles
    - Haptotaxis

- id: doi:10.3390/cells9102243
  image: images/publication/cells-09-02243-g004.jpeg
  tags:
    - delta-9-tetrahydrocannbinol (THC)
    - extracellular vesicles (EVs)
    - SIV/HIV

- id: doi:10.1016/j.apsb.2021.09.032
  image: images/publication/gr4.jpeg
  tags:
    - Fibroblast activation protein
    - Nasopharyngeal cancer
    - PET

- id: doi:10.2147/CMAR.S228174
  image: images/publication/CMAR-11-8977-g0003.jpeg
  tags:
    - TAAs
    - TME
    - gene expression score
    - glioblastoma
    - prognosis
